services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
